name: schwifty_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  http: ^0.13.5
  requests: ^4.7.0
  riverpod: ^2.1.3
  shelf_cors_headers: ^0.1.4

dev_dependencies:
  lints: ^2.0.1
  mocktail: ^0.3.0
  test: ^1.19.2
